// AUTO-GENERATED by `npm run images` (scripts/prepare-images.mjs). Do not edit by hand.
// Maps photo keys (activity slugs, "auth", "onboarding") to optimised local assets.
export type Photo = { src: string; width: number; height: number; blurDataURL: string; alt: string; position: string };

export const PHOTOS: Record<string, Photo> = {
  "running": {
    "src": "/images/photos/running.webp",
    "width": 1122,
    "height": 1402,
    "blurDataURL": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JQBdkBswYIXHLIAOiCqhlZ3SAAP7e8DUSoRbeg6DLAV4Y+tHRtkBW7VQ3Y66F5J2jk/0S/FnGdQALy9x7iS5skZG2En0oloagQdY2W3V1L498g+l0+cdhiQhhIC1rUWNo4i0yM4DK08/CKrCl47wawwAAAA==",
    "alt": "Runner sprinting along a seafront promenade at sunrise with the city skyline behind",
    "position": "55% 50%"
  },
  "gym": {
    "src": "/images/photos/gym.webp",
    "width": 1122,
    "height": 1402,
    "blurDataURL": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JYwCdMoADYH4wg7zetLF3pnhAAP7xD9lHBEidRWpemo/W9YS1k3AznL9f2d2+NM6PNvPJqTZj5Lxj7LtbS2H7cB5nGmEJ5NucusxMj7Ry/InPfrkKvVIIYChc+wuX6knvYoDBqKBt3RThYomvo4BbdwAAAA==",
    "alt": "Man doing dumbbell curls on a bench in a gym at golden hour",
    "position": "45% 50%"
  },
  "cycling": {
    "src": "/images/photos/cycling.webp",
    "width": 1122,
    "height": 1402,
    "blurDataURL": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAwBACdASoQABQAPu1iqU2ppaOiMAgBMB2JYgC7AB9u9+/AJPXdfv1lRgAA/Gb42gulXc7nhGt3yUYCblFLQJwBhr3mpP35nbH9az1toWMvsNmMAGUHD92wqf1PSjb1KzWmxYd54WhUr3WojHwPPwWbIVfwd5lSqcymscw+wi0AAA==",
    "alt": "Road cyclist riding downhill at sunset above a city by the water",
    "position": "40% 50%"
  },
  "badminton": {
    "src": "/images/photos/badminton.webp",
    "width": 1122,
    "height": 1402,
    "blurDataURL": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAABQBACdASoQABQAPu1iqU2ppaQiMAgBMB2JZQDKH8ADMuXPUYpfs+XrlHsAAP7sf3AP0ZOQAt0778FZGPL9suY+mUDy3gErPZ3Gk0QGLb1JV/WNcCxXP8xwmbob5jAER6Y4URvCkKN/djMSQOFxHoAjdURq83EoBoAAAA==",
    "alt": "Badminton player lunging for a shuttlecock on an indoor court",
    "position": "55% 50%"
  },
  "tennis": {
    "src": "/images/photos/tennis.webp",
    "width": 1122,
    "height": 1402,
    "blurDataURL": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAwBACdASoQABQAPu1iqU2ppaOiMAgBMB2JQBadA+yug69EuhbgGlA5WAAA/pcOdBek1JJ6ccJ+3pEq4EX2njCFBx6LagzzFaivuvFF/gCuVtcOiFY6TtWSxJBtN0xytUQh7Y24Q6A9Ql5bTdm8WPkqroWFU5X9M1M1cCxqr3SKXYotEAA=",
    "alt": "Tennis player hitting a backhand on an outdoor court at sunset",
    "position": "55% 50%"
  },
  "pickleball": {
    "src": "/images/photos/pickleball.webp",
    "width": 1122,
    "height": 1402,
    "blurDataURL": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAADwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JQAB8vS3kHTZOFG6eRscAAPkyyX52F/2vU3vOhR1j1Vmopw1KQ5S6FozihvUxdWLwYkGStkb3h2972eeqh8kcyEL/XYvUPHDFZv3HslikDpO1uLf26Rlm6Kaq7fSrJ8gQp3J1ciLDl71KM7Yr4AAA",
    "alt": "Pickleball player volleying the ball at the net at sunset",
    "position": "35% 50%"
  },
  "football": {
    "src": "/images/photos/football.webp",
    "width": 1122,
    "height": 1402,
    "blurDataURL": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAwBACdASoQABQAPu1iqU2ppaOiMAgBMB2JZACdMoADQwwdyuIv/5P0f/wA/q8J5zelJzbHAHm2hzd9/Ayea7GDNWS228GIChm98VscP/HKj2y/RekRAxTYyh0Eqp4GncBiKRh7qIAXeRb0BS/fCHk/oX1POEJ4cTUe9Vi9xgAAAA==",
    "alt": "Footballer striking the ball on a turf pitch at sunset",
    "position": "50% 50%"
  },
  "yoga": {
    "src": "/images/photos/yoga.webp",
    "width": 1536,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAsAA4BaJbACdADcMNDew0AA/q7r1r1wX7x5/ePbQT+7qlg/xMWInbhpJQElSrQYnXg9RANNyvBky/DQWMdjvRy8+auda5TOF9AA",
    "alt": "Woman meditating cross-legged on a yoga mat by the sea at sunset",
    "position": "34% 50%"
  },
  "swimming": {
    "src": "/images/photos/swimming.webp",
    "width": 1536,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAsAA4BaJZACdAEPUlXEQgAA9qchPQuqpKEfnsdbpQvpt3gFjLxW2gJCefLdi2aIGm71oYyWmYHhZNO+wcG5SIwpFQ8U1IIkAcr4PKneBJwA",
    "alt": "Swimmer doing front crawl in an outdoor pool at sunset",
    "position": "58% 50%"
  },
  "dance": {
    "src": "/images/photos/dance.webp",
    "width": 1536,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQAgCdASoQAAsAA4BaJZgCdAERH4r54qOgAP6ts247YtbXCvSVHRgc5VfitQrld2+b2eCsU7dVtd8MDxezlXb+p2+Sz2ySw2Ln4w4qbVdEOfFmbIPgmimjM7yiuRmlMBYLVtKuyW0AAA==",
    "alt": "Dancer in a low lunge in a mirrored studio with warm lighting",
    "position": "38% 50%"
  }
};
