#!/usr/bin/env node
/**
 * Optimises source photos for KREW and regenerates lib/photo-manifest.ts.
 *
 *   1. Put licensed source photos in assets/photos/ named by key:
 *        running, gym, cycling, badminton, tennis, pickleball, football, yoga, swimming, dance,
 *        auth (sign-up / login panel), onboarding (onboarding side panel)
 *      e.g. assets/photos/running.jpg  (jpg, jpeg, png or webp; ≥ 1600px wide recommended)
 *   2. Optionally add alt text in assets/photos/alt.json: { "running": "Runner on a seafront at sunset" }
 *   3. npm run images
 *
 *   Optional assets/photos/positions.json sets the crop focus (CSS object-position) per key.
 *
 * Output: public/images/photos/<key>.webp (max 1600px, graded to the KREW dark look)
 *         + tiny blur placeholders, written into lib/photo-manifest.ts.
 */
import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const SRC = path.join(ROOT, "assets/photos");
const OUT = path.join(ROOT, "public/images/photos");
const MANIFEST = path.join(ROOT, "lib/photo-manifest.ts");
const KEYS = ["running", "gym", "cycling", "badminton", "tennis", "pickleball", "football", "yoga", "swimming", "dance", "auth", "onboarding"];
const DEFAULT_ALT = {
  running: "Runner training outdoors",
  gym: "Person lifting weights in a gym",
  cycling: "Cyclist riding on an open road",
  badminton: "Badminton player reaching for a shuttlecock",
  tennis: "Tennis player hitting a forehand",
  pickleball: "Pickleball player at the net",
  football: "Footballer dribbling the ball",
  yoga: "Person holding a yoga pose",
  swimming: "Swimmer mid-stroke in a pool",
  dance: "Dancer mid-move in a studio",
  auth: "Friends working out together outdoors",
  onboarding: "Group of people exercising together",
};

const positions = existsSync(path.join(SRC, "positions.json")) ? JSON.parse(await readFile(path.join(SRC, "positions.json"), "utf8")) : {};
const altOverrides = existsSync(path.join(SRC, "alt.json")) ? JSON.parse(await readFile(path.join(SRC, "alt.json"), "utf8")) : {};
await mkdir(OUT, { recursive: true });
const files = existsSync(SRC) ? await readdir(SRC) : [];
const manifest = {};

for (const key of KEYS) {
  const file = files.find((f) => /\.(jpe?g|png|webp)$/i.test(f) && path.parse(f).name.toLowerCase() === key);
  if (!file) continue;
  const input = path.join(SRC, file);
  // Consistent grade: slight desaturation + contrast so every photo feels like one set.
  const pipeline = sharp(input).rotate().resize({ width: 1600, height: 1600, fit: "inside", withoutEnlargement: true })
    .modulate({ saturation: 0.85, brightness: 0.95 }).linear(1.08, -8);
  const { data, info } = await pipeline.clone().webp({ quality: 78, effort: 5 }).toBuffer({ resolveWithObject: true });
  await writeFile(path.join(OUT, `${key}.webp`), data);
  const blur = await sharp(data).resize(16).webp({ quality: 40 }).toBuffer();
  manifest[key] = {
    src: `/images/photos/${key}.webp`,
    width: info.width,
    height: info.height,
    blurDataURL: `data:image/webp;base64,${blur.toString("base64")}`,
    alt: altOverrides[key] ?? DEFAULT_ALT[key],
    position: positions[key] ?? "50% 50%",
  };
  console.log(`✓ ${key.padEnd(11)} ${info.width}×${info.height}  ${(data.length / 1024).toFixed(0)} KB`);
}

const body = `// AUTO-GENERATED by \`npm run images\` (scripts/prepare-images.mjs). Do not edit by hand.
// Maps photo keys (activity slugs, "auth", "onboarding") to optimised local assets.
export type Photo = { src: string; width: number; height: number; blurDataURL: string; alt: string; position: string };

export const PHOTOS: Record<string, Photo> = ${JSON.stringify(manifest, null, 2)};
`;
await writeFile(MANIFEST, body);
const missing = KEYS.filter((k) => !manifest[k]);
console.log(`\nWrote ${Object.keys(manifest).length} photos.${missing.length ? ` Missing (placeholder art used): ${missing.join(", ")}` : ""}`);
